### ISSUE TITLE
Upgrade to predis v2

### ISSUE THREAD

**Issue by erickdelsantos** [launchdarkly/php-server-sdk-redis-predis#12]
Are there any plans to upgrade predis to version 2?

**Comment by eli-darkly** [comment]
Yes. This was delayed due to some other PHP SDK work we've been busy with lately— there will be a new major version release of the SDK soon, which may involve some changes to how the database integrations work. But we also want people to be able to use predis v2 with the current major version of the SDK, so we will probably be doing two releases of this package: one that just updates predis, and then one that also includes any necessary changes for the new SDK.

**Comment by eli-darkly** [comment]
We've released version 1.2.0, which supports both v1 and v2 of Predis— it turned out that there weren't any relevant API differences that would make this change backward-incompatible.
